# fly.toml app configuration file generated for the-qotd on 2023-05-21T13:33:19+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "the-qotd"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
